# -*- coding: utf-8 -*-
"""Zeroshot_anger_label_streamlit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GZCaVupofyN3isegi89dQCNgPilswaNg
"""

#!pip install streamlit

#!pip install transformers==3.1.0

import streamlit as st
from transformers import pipeline
def input_data():
    user_input=st.text_input("Enter the sentence here")
    return user_input
@st.cache
def get_pipeline():
    classifier = pipeline("zero-shot-classification")
    return classifier

def zero_shot(user_input,user_label_split):
    st.write("success")
    classifier=get_pipeline()
    result=classifier(user_input, user_label_split,multi_class=True)
    st.write(result)
def main():
    user_input=input_data()
    user_label_split=['sad','happy','angry','disappointmet','annoyed','excited','satisfied']
    zero_shot(user_input,user_label_split)

if __name__ == "__main__":
    st.title("Automatic Data Labelling")
    st.write("Zero-shot classification for automatic Data Labelling")
    

    # App title and description
    
    

