# -*- coding: utf-8 -*-
"""Zeroshot_anger_label_streamlit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GZCaVupofyN3isegi89dQCNgPilswaNg
"""

#!pip install streamlit

#!pip install transformers==3.1.0

import streamlit as st
from transformers import pipeline


if __name__ == "__main__":
    user_input=st.text_input("Enter the sentence here")

    user_label_split=['sad','happy','angry','disappointmet','annoyed','excited','satisfied']

    # App title and description
    st.title("Automatic Data Labelling")
    st.write("Zero-shot classification for automatic Data Labelling")
    classifier = pipeline("zero-shot-classification")
    st.write("success")
    result=classifier(user_input, user_label_split,multi_class=True)
    st.write(result)

